apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: app
  namespace: kargo-blue-green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: rollouts-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
