apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: rollouts-demo
  namespace: kargo-blue-green
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/akuity/rollouts-demo
      imageSelectionStrategy: NewestBuild
